FROM node:14.15.4-alpine
WORKDIR /usr/app
COPY . .
ARG _API_KEY
ARG _NEXT_PUBLIC_API_KEY
ARG _NEXT_PUBLIC_STRAPI_API_URL
ARG _NEXT_PUBLIC_MAPBOX_API_TOKEN
ENV API_KEY=$_API_KEY
ENV NEXT_PUBLIC_API_KEY=$_NEXT_PUBLIC_API_KEY
ENV NEXT_PUBLIC_STRAPI_API_URL=$_NEXT_PUBLIC_STRAPI_API_URL
ENV NEXT_PUBLIC_MAPBOX_API_TOKEN=$_NEXT_PUBLIC_MAPBOX_API_TOKEN
RUN echo $API_KEY
RUN echo $NEXT_PUBLIC_API_KEY
RUN echo $NEXT_PUBLIC_STRAPI_API_URL
RUN npm ci --only=production
RUN npm run build
CMD ["npm","start"]
